name: wp-twin-tails
recipe: wordpress
config:
  webroot: web
  database: mysql
  via: nginx
  php: '8.0'
  xdebug: true

services:
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver

proxy:
  mailhog:
    - mail.wp-twin-tails.lndo.site

tooling:
  install:wordpress:
    service: appserver
    cmd:
      - wp core install --url="http://wp-twin-tails.lndo.site" --title="twin-tails" --admin_user=admin --admin_password=password --admin_email=admin@example.org