name: testing
recipe: wordpress
config:
  webroot: web
  database: mysql
  via: nginx
  php: '7.4'
  xdebug: true

services:
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver

proxy:
  mailhog:
    - mail.testing.lndo.site